spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none #<!--하이버네이트로 데이터베이스 스키마를 생성하는 방법을 제어하는 옵션
    database-platform: org.hibernate.dialect.H2Dialect #스프링부트에서 jpa를 사용해서 데이터베이스를 다룰 때, 하이버네이트에서 사용할 데이터베이스 플랫폼을 지정하는 옵션

  sql:
    init:
      mode: always #appliation 시작할 때 초기 sql 스크립트 실행하는 방법을 지정, 항상 실행하겠다
      platform: h2

  datasource:
    url: jdbc:h2:mem:development;Mode=MYSQL;DB_CLOSE_DELAY=1
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console